name: Build, push and sign
on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - "*.md"

jobs:
  build_push_sign:
    permissions:
      contents: "read"
      id-token: "write"
    outputs:
      img_to_deploy: "europe-north1-docker.pkg.dev/nais-io/nais/images/tokendings@${{ steps.build-push.outputs.digest }}"
      img_version: "${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # ratchet:actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # ratchet:actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Verify Gradle wrapper checksum
        uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # ratchet:gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          access_token_lifetime: 300s
          workload_identity_provider: ${{ vars.WORKLOAD_PROVIDER_ID }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}


        # Setting up Docker Buildx with docker-container driver is required
        # at the moment to be able to use a subdirectory with Git context
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            europe-north1-docker.pkg.dev/${{ vars.PROJECT_ID }}/the-new-empire/tokendings:${{ steps.get-tag.outputs.short_ref }}
            europe-north1-docker.pkg.dev/${{ vars.PROJECT_ID }}/the-new-empire/tokendings:dev
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
            "github_actor=${{ github.actor }}"
